language: php

php:
    - 5.3
    - 5.4

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update
  - cp ./Tests/Functional/config/parameters.yml.dist ./Tests/Functional/config/parameters.yml
  - php Tests/Functional/console doctrine:phpcr:init:dbal
  - php Tests/Functional/console doctrine:phpcr:repository:init

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
